version: "3.9"

services:
  counter-service:
    image: $REGISTRY:${TAG}
    ports:
      - "80:8000"
    networks:
      - counter-service
    depends_on:
      - redis
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
  redis:
    image: redis:6.0.9
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    command: redis-server --appendonly yes
    networks:
      - counter-service
networks:
  counter-service:
    driver: overlay
    attachable: true
volumes:
  redis:

