version: "3.9"

services:
  counter-service:
    image: counter-service:latest
    networks:
      - counter-service
  redis:
    image: redis:6.0.9
    networks:
      - counter-service

networks:
  counter-service:
    driver: overlay
    attachable: true

